name: Common Pull Request Checks

on:
  pull_request:
    branches:
      - "**"

permissions: write-all

jobs:
  common-pull-request-checks:
    uses: neteye-platform/repo-commons/.github/workflows/common-pull-request-checks.yaml@92240df2505b2acee9a811a828411bc81bf388f7 # main
    secrets: inherit
